### ISSUE TITLE
Get all work into a Mindset package and Mindset namespace in 1909 system.

### ISSUE THREAD

**Issue by jdbragg** [MindsetConsulting/MindsetAppAnalyzerFree#18]
Includes:
- Code base
- SICF nodes
- GW service
- Tables
- Security roles
- FLP config

**Comment by esjewett** [comment]
Just a quick comment (I'm spying - sorry) - I'd suggest separate packages for each of the following:

- Backend service(s) - split into different packages if functionally separate
- Fiori Launchpad Plugin
- Fiori Application

Supporting objects for each should go into their own packages. For example SICF nodes and MIME repository objects for the Fiori app should go into the app's package.

It's fine if all of these packages are sub-packages of a super-package. And yes, I'd agree they should all be in the Mindset namespace.

**Comment by jdbragg** [comment]
I hope you like what you see.  Matthew's going through today and renaming/repackaging the content of the App Analyzer.  It will no longer have any references to Fiori Monitor btw...  But yes overall, the package in my definition should include everything that is needed for a specific application to run.  Service, SICF nodes, app code, etc...  In the case of our analyzer, I think I would still package the FLP plugin together since they serve the same piece of deploy-able software and 1 can't really work without the other, but I could be convinced otherwise if you both think that's the best course of action.

**Comment by esjewett** [comment]
@jdbragg They need to be in separate packages because you don't want to include the UI5 app in the ABAPGit repository for the backend stuff. It's fine if one or the other (or both) are in a sub-package, but generally you'll want to keep the ABAP/backend stuff in a separate package from the UI5/frontend stuff. I'd recommend something like:

- ZMYAPP
-- ZMYAPPUI5
-- ZMYAPPODATA

**Comment by jdbragg** [comment]
Got it, thanks.  We can do that.  @msw009  let me know if you have any other thoughts on this structure:  Would make the super package:  /mindset/app_analyzer and subpackage /mindset/app_analyzerUI5 etc..etc...
