### ISSUE TITLE
Ability to perform an ABAPGit install for backend code

### ISSUE THREAD

**Issue by jdbragg** [MindsetConsulting/MindsetAppAnalyzerFree#25]

**Comment by esjewett** [comment]
This appears to be working in the `abapgit-artifacts` branch. Pull request #17

**Comment by jdbragg** [comment]
Based on testing and overview yesterday with Ethan, I think this can be closed.  ABAPGit successfully retrieves the repository and we have packaged code so that a user can choose to only import the backend service and code vs. UI5 apps which should be deployed from WebIDE.  This is a secondary option for developers looking to install the application without needing to import the transport.
