### ISSUE TITLE
As a monitoring user, when I click on the application usage card I need to see a list report of application details.

### ISSUE THREAD

**Issue by jdbragg** [MindsetConsulting/MindsetAppAnalyzerFree#4]
- Clicking the graph (app) line item in the appviews card will navigate to a detailed page.
- In the detailed page I need to see application details:  
    - Usernames logged into the app
    - Time in app
    - Number of time accessing this app
    -

**Comment by msw009** [comment]
we added a popup details table that shows a snapshot of user data
