### ISSUE TITLE
As a monitoring user, I need to see details for a specific application when I click within the AppViews by app card.

### ISSUE THREAD

**Issue by jdbragg** [MindsetConsulting/MindsetAppAnalyzerFree#51]
When I click on a specific application in the AppViews by app card, I should be navigated to the detail application (analyzer detail), that shows details by application:

Application Name, User Name, Browser Type, Device Type, number of accesses, application response time, last access.

Future functionality to show # of accesses over time, Employee Experience metrics, etc...

**Comment by msw009** [comment]
Added Navigation to detail app inside the popover. we HAVE NOT added filtering based on app selected.
